### ISSUE TITLE
orjson is not compatible with PyPy

### ISSUE THREAD

**Issue by stonebig** [martinRenou/ipycanvas#201]
could ipycanvas rely on something else than orjson when running on PyPy ?

orjson is not compatible with PyPy  https://github.com/ijl/orjson#will-it-support-pypy

**Comment by martinRenou** [comment]
Thanks for opening this issue.

Another reason for getting rid of orjson is compatibility with [jupyterlite](https://github.com/jtpio/jupyterlite), ipycanvas won't be installable on jupyterlite unless orjson is not a dependency.

The problem is orjson is *super* fast, so maybe we should not make it a hard dependency, and fallback on another JSON library if it's not found, but still use it if it's found.

**Comment by martinRenou** [comment]
Would rapidjson be a good replacement in your opinion?

**Comment by stonebig** [comment]
I need something compatible  with pypy3.7 on Windows.

Performance is not the concern.

**Comment by martinRenou** [comment]
I implemented a fallback to the Python standard `json` library. I understand pypy's json library should be faster. 

I've never looked into building a pypy package on conda-forge. Is it something you'd be able/willing to work on?

**Comment by stonebig** [comment]
I'm not on conda.  I'm on pypi.
