### ISSUE TITLE
Game of Life example with Voila

### ISSUE THREAD

**Issue by jtpio** [martinRenou/ipycanvas#56]
So I wanted to run the Game of Life example with Voila, but it seems to be partially working (haven't investigated the cause yet).

![ipycanvas-voila](https://user-images.githubusercontent.com/591645/68333622-2791ef00-00d9-11ea-90a4-854280a556f7.gif)

To test it on Binder:

- Gist: https://gist.github.com/jtpio/ac9fa41239fd0098ede03ec042aec574
- Binder: https://mybinder.org/v2/gist/jtpio/ac9fa41239fd0098ede03ec042aec574/master?urlpath=%2Fvoila%2Frender%2Fgol.ipynb

**Comment by martinRenou** [comment]
Yes, it's unfortunately a known issue. ipycanvas relies on comm messages for draw commands. But until the client is ready to receive comm message all the messages that are sent during the execution of the Notebook are lost in the void...

This results in the Game Of Life example to partially work, but it's actually a lucky one because other examples would not work at all (The Game Of Life example works because it keeps sending new messages due to the infinite rendering loop).

I added a small section in the documentation dedicated to Voila: https://ipycanvas.readthedocs.io/en/latest/advanced.html#ipycanvas-in-voila

**Comment by martinRenou** [comment]
Since we added the `image_data` trait to the Canvas, we could use it as a "state" for the Canvas and fix this issue. But there would still be an issue concerning the real state of the Canvas (fill and stroke style, shadows, line styles etc.).

**Comment by jtpio** [comment]
Oh I missed that part of the documentation, thanks!

But yes the fact that the client is not ready can also be an issue for other widgets.
