### ISSUE TITLE
What is the effect of caching?

### ISSUE THREAD

**Issue by acnazarejr** [martinRenou/ipycanvas#92]
I didn't understand the effect of caching argument in the Canvas class constructor. There are examples illustrate examples when caching is enable or not?

**Comment by martinRenou** [comment]
I actually did not really expose the `caching` argument to the documentation or anything. You can use the argument manually if you want, but the best way of using caching is to use the `hold_canvas` context manager.

The `hold_canvas` context manager [uses the caching](https://github.com/martinRenou/ipycanvas/blob/master/ipycanvas/canvas.py#L674) in order to cache all commands during the context and [flush them at the end](https://github.com/martinRenou/ipycanvas/blob/master/ipycanvas/canvas.py#L676). This way, only one message is sent to the web-page, containing all draw commands.

You can do all this manually if you want using the `caching` attribute and the `flush` method.
